from pathlib import Path

# from PyQt6.QtCore             import (Qt,
#                                       pyqtSlot)
# from PyQt6.QtWidgets          import (QLabel,
#                                       QVBoxLayout)
# from PyQt6.QtGui              import (QPixmap)

from PySide6.QtCore       import (Qt,
                                  Slot)
from PySide6.QtWidgets    import (QLabel,
                                  QVBoxLayout)
from PySide6.QtGui        import (QPixmap)
from PySide6.QtSvgWidgets import QSvgWidget

from svg_metadata_reader import SvgMetadataReader


class Visualiser_Panel_Plot_View(QSvgWidget) :

    def __init__(self) :

        nameMethod = self.__class__.__name__ + \
                     "::__init__"

        return_code = True


        print(nameMethod + " : Enter")

        super().__init__()

        # - Create the child widgets for this widget.
        # - Create, set, and setup the layout for this widget.

        # self.__create_child_widgets()
        # self.__setup_layout()

        # self.load_current_image_into_panel()

        print(nameMethod + " : Exit")


    def __check_filename(self, filename) :

        file_path = Path(filename)

        if filename is None :

            raise Exception("filename is empty")

        if not file_path.is_file() :

            raise Exception("Filename does not exist : " + filename)

        return True


    def set_filename(self, filename) :

        if self.__check_filename(filename) :

            self.filename_plot = filename


    def __create_child_widgets(self) :

        nameMethod = self.__class__.__name__ + \
                     "::create_child_widgets"


        print(nameMethod + " : Enter")

        # self.image             = QPixmap()
        self.image             = QSvgWidget()
        self.svgMetadataReader = SvgMetadataReader()

        print(nameMethod + " : Exit")


    def __setup_layout(self) :

        nameMethod = self.__class__.__name__ + \
                     "::setup_layout"


        print(nameMethod + " : Enter")

        # Create, set, and configure the layout for this widget.

        layout = QVBoxLayout()

        self.setLayout(layout)
        self.layout().addWidget(self.image)

        print(nameMethod + " : Exit")


    def load_current_image_into_panel(self) :

        nameMethod = self.__class__.__name__ + \
                     "::load_current_image_into_panel"


        print(nameMethod + " : Enter")

        # - Check that the file named by the current filename is valid.
        # - Update the view panel with the image in this file.

        self.__check_filename(self.filename_plot)
        self.slot_update_panel(self.filename_plot)

        print(nameMethod + " : Exit")


    def load_image_into_panel(self, filename) :

        nameMethod = self.__class__.__name__ + \
                     "::load_image_into_panel"


        print(nameMethod + " : Enter")

        self.__check_filename(filename)
        self.slot_update_panel(self.filename_plot)

        print(nameMethod + " : Exit")


    """
    This method is intentionally defined as a slot.
    
    The reason for this is because this slot runs in the GUI thread, but
    the code which signals it runs in a separate animation thread.
    
    This way, the two methods involved are loosely coupled.
    
    ========================================
    
    This method can throw exceptions.
    
    They can be generated by the following lines of code.
    
      - self.svgMetadataReader.get_parameters_from_file
      - self.__open_image(filename)
      
    """

    @Slot(str)
    def slot_update_panel(self, filename) :

        nameMethod = self.__class__.__name__ + \
                     "::slot_update_panel"


        print(nameMethod + " : Enter")
        print(nameMethod + " : Arg filename = " + filename)

        self.__check_filename(filename)

        # Get the metadata from the image file.
        #
        #   - Can throw an exception.

        self.parameters = self.svgMetadataReader.get_parameters_from_file(filename, True)

        # Open the image file and then load it into the panel.

        self.__open_image(filename)

        # Get the width, height, and size of the label.

        if False :

            widthLabelImage  = self.width()
            heightLabelImage = self.height()
            sizeLabelImage   = self.size()

            print(nameMethod + " : Width of image  = " + str(widthLabelImage))
            print(nameMethod + " : Height of image = " + str(heightLabelImage))
            print(nameMethod + " : Size of image   = " + str(sizeLabelImage))

            imageScaled = self.image.scaled(sizeLabelImage,
                                            Qt.AspectRatioMode.KeepAspectRatio,
                                            Qt.TransformationMode.SmoothTransformation)

            self.setPixmap(imageScaled)
            self.setScaledContents(True)

        # Schedule a repaint of this widget.
        #
        # We do this because an image has just been loaded into it.

        self.update()
        self.image.show()

        # print("Image label width  = ", widthLabelImage)
        # print("Image label height = ", heightLabelImage)

        # TODO : Uncomment this when ready.

        # self.update_panel_side()


        print(nameMethod + " : Exit")


    def __open_image(self, filename) :

        nameMethod = self.__class__.__name__ + \
                     "::__open_image"


        print(nameMethod + " : Enter")

        self.image = QSvgWidget(filename)

        if self.image is None :

            raise Exception("Problem loading image from file : " + str(filename))


        print(nameMethod + " : Exit")

        return
